const Erros = {
	USUARIO_JA_EXISTE: "USUARIO_JA_EXISTE",
	USUARIO_NAO_EXISTE: "USUARIO_NAO_EXISTE",
	SENHA_OBRIGATORIA: "SENHA_OBRIGATORIA",
	CREDENCIAIS_INCORRETAS: "CREDENCIAIS_INCORRETAS",
	ACESSO_NEGADO: "ACESSO_NEGADO",
} as const;

export default Erros;
